backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

from signup import urls as signup_urls

urlpatterns = [
    url(r'', include(signup_urls, namespace='signup')),
    path('admin/', admin.site.urls),
]

signup/urls.py
from django.conf.urls import url
from . import views

app_name = 'signup'

urlpatterns = [
    url(r'^create/', views.signup, name='signup'),
    url(r'^login/', views.login_func, name='login'),
    url(r'^makeup_regis/', views.makeup_regis, name='makeup_regis')

]

signup/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField


class Accounts(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10)
    choices = (
        ('Influencer', 'Influencer'),
        ('Makeup Artist', 'Makeup Artist'),
        ('Photographer', 'Photographer')
    )

    profile_category = models.CharField(max_length=255, choices=choices)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Accounts.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.accounts.save()


class MakeupList(models.Model):
    account = models.OneToOneField(Accounts, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=False)
    email = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    contact_number = PhoneNumberField(null=False, blank=False, unique=True)
    dob = models.DateField(blank=False)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others')
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    location = models.CharField(max_length=50, blank=False)
    cat1 = "Social Media Markup Artist"
    cat2 = "Freelancer"
    cat3 = "Student"
    cat4 = "Working Professional"
    CATEGORY_CHOICES = (
        (cat1, "Social Media Markup Artist"), (cat2, "Freelancer"), (cat3, "Student"), (cat4, "Working Professional"))
    category = models.CharField(choices=CATEGORY_CHOICES, blank=False,  max_length=40)
    instagram_username = models.CharField(max_length=256, default="")
    instagram_followers = models.IntegerField(default=0)
    twitter_username = models.CharField(max_length=256, blank=True, null=True)
    twitter_followers = models.IntegerField(blank=True, null=True)
    facebook_username = models.CharField(max_length=256, blank=True, null=True)
    facebook_followers = models.IntegerField(blank=True, null=True)
    youtube_username = models.CharField(max_length=256, blank=True, null=True)
    youtube_followers = models.IntegerField(blank=True, null=True)
    linkedin_username = models.CharField(max_length=256, blank=True, null=True)
    linkedin_followers = models.IntegerField(blank=True, null=True)
    snapchat_username = models.CharField(max_length=256, blank=True, null=True)
    snapchat_followers = models.IntegerField(blank=True, null=True)
    pinterest_username = models.CharField(max_length=256, blank=True, null=True)
    pinterest_followers = models.IntegerField(blank=True, null=True)
    tumbler_username = models.CharField(max_length=256, blank=True, null=True)
    tumbler_followers = models.IntegerField(blank=True, null=True)
    github_username = models.CharField(max_length=256, blank=True, null=True)
    github_followers = models.IntegerField(blank=True, null=True)
    dribble_username = models.CharField(max_length=256, blank=True, null=True)
    dribble_followers = models.IntegerField(blank=True, null=True)
    reddit_username = models.CharField(max_length=256, blank=True, null=True)
    reddit_followers = models.IntegerField(blank=True, null=True)
    weddingmakeup = models.BooleanField(default=True)
    clinicalmedicine = models.BooleanField(default=False)
    facepaint = models.BooleanField(default=False)
    filmsandmovie = models.BooleanField(default=False)
    influencermakeup = models.BooleanField(default=False)
    skincare = models.BooleanField(default=False)
    bank_Full_Name = models.CharField(max_length=256, default="")
    bank_acccount_number = models.BigIntegerField()
    bank_IFSC_code = models.CharField(max_length=11, default="")
    paytm_Full_Name = models.CharField(max_length=256, blank=True, null=True)
    paytm_Number = models.IntegerField(blank=True, null=True)
    gpay_Full_Name = models.CharField(max_length=256, blank=True, null=True)
    gpay_Number = models.IntegerField(blank=True, null=True)
    upi_Full_Name = models.CharField(max_length=256, blank=True, null=True)
    upi_ID = models.CharField(max_length=60, blank=True, null=True)
    sms_agency_name = models.CharField(max_length=256, blank=True, null=True)
    sms_agent_name = models.CharField(max_length=256, blank=True, null=True)
    sms_agent_email = models.EmailField(blank=True, null=True)
    sms_agent_number = PhoneNumberField(blank=True, null=True)
    free_assign_done = models.CharField(blank=True, null=True, max_length=40)
    free_no_experience = models.CharField(blank=True, null=True, max_length=40)
    free_date_assign = models.CharField(blank=True, null=True, max_length=42)
    ca_college_name = models.CharField(blank=True, null=True, max_length=256)
    ca_capacity = models.CharField(blank=True, null=True, max_length=256)
    ca_course = models.CharField(blank=True, null=True, max_length=256)
    ca_committee = models.CharField(blank=True, null=True, max_length=256)
    YEAR_OF_STUDY = (("First Year", "First Year"), ("Second Year", "Second Year"), ("Third Year", "Third Year"),
                     ("Forth Year", "Forth Year"), ("Fifth Year", "Fifth Year"))
    ca_year_of_study = models.CharField(choices=YEAR_OF_STUDY, blank=True, null=True, max_length=100)
    ca_worked_hobnob = models.CharField(blank=True, null=True, max_length=45)
    wp_company_name = models.CharField(blank=True, null=True, max_length=256)
    wp_designation = models.CharField(blank=True, null=True, max_length=256)

    def __str__(self):
        return '{}\t{}'.format(self.name, self.category)

signup/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import MakeupList


class SignUpForm(UserCreationForm):
    phone_number = forms.CharField()
    choices = (
        ('Influencer', 'Influencer'),
        ('Makeup Artist', 'Makeup Artist'),
        ('Photographer', 'Photographer')
    )
    profile_category = forms.ChoiceField(choices=choices)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'phone_number', 'profile_category', 'first_name')
        labels = {
            'first_name': 'Name',
            'username': 'Email Address'
        }


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'password')


class DateInput(forms.DateInput):
    input_type = 'date'


class MakeupForm(forms.ModelForm):
    class Meta:
        model = MakeupList
        exclude = ['account', 'email']
        fields = "__all__"
        labels = {
            'location': 'Address',
        }
        widgets = {
            'dob': DateInput(),
            'location': forms.TextInput(attrs={'placeholder': 'Location'}),
            'contact_number': forms.TextInput(attrs={'placeholder': 'Mobile Number'}),
            'bank_Full_Name': forms.TextInput(attrs={'placeholder': "Account Holder's Full Name"}),
            'bank_acccount_number': forms.TextInput(attrs={'placeholder': 'Account Number'}),
            'bank_IFSC_code': forms.TextInput(attrs={'placeholder': 'IFSC code'}),
            'paytm_Full_Name': forms.TextInput(attrs={'placeholder': 'Full Name'}),
            'paytm_Number': forms.TextInput(attrs={'placeholder': 'Paytm Number'}),
            'gpay_Full_Name': forms.TextInput(attrs={'placeholder': 'Full Name'}),
            'gpay_Number': forms.TextInput(attrs={'placeholder': 'Gpay Number'}),
            'upi_Full_Name': forms.TextInput(attrs={'placeholder': 'Full Name'}),
            'upi_ID': forms.TextInput(attrs={'placeholder': 'UPI ID'}),
            'sms_agency_name': forms.TextInput(attrs={'placeholder': 'Agency Name'}),
            'sms_agent_name': forms.TextInput(attrs={'placeholder': 'Agent Name'}),
            'sms_agent_email': forms.EmailInput(attrs={'placeholder': 'Your Agent Email ID'}),
            'sms_agent_number': forms.TextInput(attrs={'placeholder': 'Agent Number'}),
            'free_assign_done': forms.TextInput(attrs={'placeholder': 'No of Assignments Done'}),
            'free_no_experience': forms.TextInput(attrs={'placeholder': 'No of years of experience'}),
            'free_date_assign': forms.TextInput(attrs={'placeholder': 'Date of Last Assignment'}),
            'ca_college_name': forms.TextInput(attrs={'placeholder': 'College Name'}),
            'ca_capacity': forms.TextInput(attrs={'placeholder': 'What capacity were/are you involved'}),
            'ca_committee': forms.TextInput(attrs={'placeholder': 'Which committees/societies'}),
            'ca_course': forms.TextInput(attrs={'placeholder': 'Course'}),
            'ca_worked_hobnob': forms.TextInput(attrs={'placeholder': 'Have You Worked with Hobnob'}),
            'wp_company_name': forms.TextInput(attrs={'placeholder': 'Company Name'}),
            'wp_designation': forms.TextInput(attrs={'placeholder': 'Designation'}),
        }

    def __str__(self):
        self.email = User.objects.order_by('-id')[0].email

signup/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, Http404
from signup.forms import SignUpForm, LoginForm, MakeupForm
from django.http import HttpResponse
from .models import MakeupList, User, Accounts
from django.db import IntegrityError

from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend


def validateEmail(email):
    from django.core.validators import validate_email
    from django.core.exceptions import ValidationError
    try:
        validate_email(email)
        return True
    except ValidationError:
        return False


def login_func(request):
    if request.method == 'POST':

        form = LoginForm(request.POST)

        if form.is_valid():
            # form.save()

            username_email = form.cleaned_data.get('email')

            if validateEmail(username_email):
                password = form.cleaned_data.get('password')
                user = authenticate(request, username=username_email, password=password)
                if user is not None and user.accounts.profile_category == "Makeup Artist":
                    login(request, user)
                    return redirect('signup:makeup_regis')
                else:
                    return HttpResponse("error logging in")
            else:
                return HttpResponse("email id not valid")
        else:
            return HttpResponse('Form is not valid')
    else:
        form = LoginForm()

    return render(request, 'signup/login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal

            user.accounts.phone_number = form.cleaned_data.get('phone_number')
            user.accounts.profile_category = form.cleaned_data.get('profile_category')
            # user.save()
            raw_password = form.cleaned_data.get('password1')

            if validateEmail(user.username):
                user.email = user.username
                user.save()
                user = authenticate(username=user.username, password=raw_password)
                if user is not None:
                    login(request, user)
                    return redirect('signup:login')
                else:
                    return redirect('myapp:signup')
            else:
                return HttpResponse("Invalid username")

    else:
        form = SignUpForm()
    return render(request, 'signup/signup.html', {'form': form})


def makeup_regis(request):
    if request.method == 'GET':
        template = 'signup/makeup3.html'
        user_name = request.user.first_name
        user_email = request.user.username
        # user_phone = Accounts.objects.order_by('-id')[0].phone_number
        user_phone = Accounts.objects.filter(phone_number=request.user.accounts.phone_number).first()
        print(user_phone)
        data = {'form': MakeupForm(), 'user_name': user_name, 'user_email': user_email, 'user_phone': user_phone}
        return render(request, template, data)
    elif request.method == 'POST':
        form = MakeupForm(request.POST)
        account_name = User.objects.order_by('-id')[0]
        account = Accounts.objects.order_by('-id')[0]
        if form.is_valid() and request.user.is_authenticated:
            fx = form.cleaned_data
            x = MakeupList(
                account=account,
                # account = request.user.username,
                name=fx['name'],
                email=account_name,
                contact_number=fx['contact_number'],
                dob=fx['dob'],
                gender=fx['gender'],
                location=fx['location'],
                category=fx['category'],
                instagram_username=fx['instagram_username'],
                instagram_followers=fx['instagram_followers'],
                twitter_username=fx['twitter_username'],
                twitter_followers=fx['twitter_followers'],
                facebook_username=fx['facebook_username'],
                facebook_followers=fx['facebook_followers'],
                youtube_username=fx['youtube_username'],
                youtube_followers=fx['youtube_followers'],
                linkedin_username=fx['linkedin_username'],
                linkedin_followers=fx['linkedin_followers'],
                snapchat_username=fx['snapchat_username'],
                snapchat_followers=fx['snapchat_followers'],
                pinterest_username=fx['pinterest_username'],
                pinterest_followers=fx['pinterest_followers'],
                tumbler_username=fx['tumbler_username'],
                tumbler_followers=fx['tumbler_followers'],
                github_username=fx['github_username'],
                github_followers=fx['github_followers'],
                dribble_username=fx['dribble_username'],
                dribble_followers=fx['dribble_followers'],
                reddit_username=fx['reddit_username'],
                reddit_followers=fx['reddit_followers'],
                weddingmakeup=fx['weddingmakeup'],
                clinicalmedicine=fx['clinicalmedicine'],
                facepaint=fx['facepaint'],
                filmsandmovie=fx['filmsandmovie'],
                influencermakeup=fx['influencermakeup'],
                skincare=fx['skincare'],
                bank_Full_Name=fx['bank_Full_Name'],
                bank_acccount_number=fx['bank_acccount_number'],
                bank_IFSC_code=fx['bank_IFSC_code'],
                paytm_Full_Name=fx['paytm_Full_Name'],
                paytm_Number=fx['paytm_Number'],
                gpay_Full_Name=fx['gpay_Full_Name'],
                gpay_Number=fx['gpay_Number'],
                upi_Full_Name=fx['upi_Full_Name'],
                upi_ID=fx['upi_ID'],
                sms_agency_name=fx['sms_agency_name'],
                sms_agent_name=fx['sms_agent_name'],
                sms_agent_email=fx['sms_agent_email'],
                sms_agent_number=fx['sms_agent_number'],
                free_assign_done=fx['free_assign_done'],
                free_no_experience=fx['free_no_experience'],
                free_date_assign=fx['free_date_assign'],
                ca_college_name=fx['ca_college_name'],
                ca_capacity=fx['ca_capacity'],
                ca_course=fx['ca_course'],
                ca_committee=fx['ca_committee'],
                ca_year_of_study=fx['ca_year_of_study'],
                ca_worked_hobnob=fx['ca_worked_hobnob'],
                wp_company_name=fx['wp_company_name'],
                wp_designation=fx['wp_designation'],
            )
            try:
                x.save()
            except IntegrityError:
                raise Http404("Integrity Error")
            else:
                return HttpResponse("MakeupArtist Created")
        else:
            template = 'signup/error.html'
            data = {'form_error': form, 'form_error_field': form.errors}
            return render(request, template, data)

signup/templates/signup/error.html
<!DOCTYPE html>
{% load static %}
<html class="loading" lang="en" data-textdirection="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description"
          content="Modern admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities with bitcoin dashboard.">
    <meta name="keywords"
          content="admin template, modern admin template, dashboard template, flat admin template, responsive admin template, web app, crypto dashboard, bitcoin dashboard">
    <meta name="author" content="PIXINVENT">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Italianno&display=swap" rel="stylesheet">


    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/app.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/vertical-menu-modern.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/boothstrap.css' %}">
    <!--    static css end -->


    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/profile-step1.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/profile-step2.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/profile-step3.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signup/css/profile-step4.css' %}">


    <!--  font-->
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@692&display=swap" rel="stylesheet">
</head>
<body class="vertical-layout vertical-menu-modern 2-columns   menu-expanded fixed-navbar"
      data-open="click" data-menu="vertical-menu-modern" data-col="2-columns">
<!-- fixed-top-->
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-dark navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a
                        class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="fa fa-bars"
                                                                                         aria-hidden="true"></i></a>
                </li>
                <li class="nav-item mr-auto">
                    <a class="navbar-brand" href="index.html">
                        <img class="brand-logo" alt="modern admin logo" src="{% static 'signup/img/logo.png' %}">
                        <h3 class="brand-text" style="font-family: 'Italianno', cursive; font-size: 45px;">Hobnob</h3>
                    </a>
                </li>
                <li class="nav-item d-none d-md-block float-right"><a class="nav-link modern-nav-toggle pr-0"
                                                                      data-toggle="collapse"><i
                        class="fa fa-toggle-on font-medium-3 white" data-ticon="ft-toggle-right"></i></a></li>
                <li class="nav-item d-md-none">
                    <a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i
                            class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
                </li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><span
                            style="font-family: 'Italianno', cursive; font-size: 60px;">Nexus Of Success</span></li>

                </ul>
                <ul class="nav navbar-nav float-right">
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                <span class="mr-1">Hello,
                  <span class="user-name text-bold-700">{{ form.user_name }}</span>
                </span>
                            <span class="avatar avatar-online">
                  <img src="{% static 'signup/img/avatar.png' %}" alt="avatar"><i></i></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="#"><i
                                class="icon-user"></i> Edit Profile</a>

                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#"><i class="fa fa-power-off" aria-hidden="true"></i> Logout</a>
                        </div>
                    </li>

                    <li class="dropdown dropdown-notification nav-item">
                        <a class="nav-link nav-link-label" href="#" data-toggle="dropdown"><i class="fa fa-bell-o"
                                                                                              aria-hidden="true"></i>

                        </a>
                        <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                            <li class="dropdown-menu-header">
                                <h6 class="dropdown-header m-0">
                                    <span class="grey darken-2">Notifications</span>
                                </h6>

                            </li>
                        </ul>
                    </li>
                    <li class="dropdown dropdown-notification nav-item">
                        <a class="nav-link nav-link-label" href="#" data-toggle="dropdown"><i class="fa fa-envelope-o"
                                                                                              aria-hidden="true"></i></a>
                        <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
                            <li class="dropdown-menu-header">
                                <h6 class="dropdown-header m-0">
                                    <span class="grey darken-2">Messages</span>
                                </h6>

                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>
<!-- ////////////////////////////////////////////////////////////////////////////-->
<div class="main-menu menu-fixed menu-dark menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation">

            <li class=" nav-item">
                <a href="campaigns.html"><img src="{% static 'signup/img/icon/campaign.png' %}" width="30px;"
                                              height="30px;"></img> &nbsp;<span class="menu-title">Campaigns</span></a>
            </li>
            <li class=" nav-item active">
                <a href="profile.html"><img src="{% static 'signup/img/icon/profile.png' %}" width="30px;"
                                            height="30px;"></img> &nbsp;<span class="menu-title">Profile</span></a>
            </li>
            <li class=" nav-item">
                <a href="branding.html"><i class="fa fa-deviantart" aria-hidden="true"></i><span class="menu-title">Branding</span></a>
            </li>
            <li class=" nav-item">
                <a href="deliverable.html"><img src="{% static 'signup/img/icon/deliverable.png' %}" width="30px;"
                                                height="30px;"></img> &nbsp;<span class="menu-title">Deliverable</span></a>
            </li>
            <li class=" nav-item">
                <a href="hashtags.html"><img src="{% static 'signup/img/icon/Hashtag.png' %}" width="30px;"
                                             height="30px;"></img> &nbsp;<span class="menu-title">Hashtags</span></a>
            </li>
            <li class=" nav-item">
                <a href="calender.html"><img src="{% static 'signup/img/icon/Calendar.png' %}" width="30px;"
                                             height="30px;"></img> &nbsp;<span class="menu-title">Calender</span></a>
            </li>
            <li class=" nav-item">
                <a href="journey.html"><img src="{% static 'signup/img/icon/journey.png' %}" width="30px;"
                                            height="30px;"></img> &nbsp;<span class="menu-title">Journey</span></a>
            </li>
            <li class=" nav-item">
                <a href="finance.html"><img src="{% static 'signup/img/icon/financial.png' %}" width="30px;"
                                            height="30px;"></img> &nbsp;<span class="menu-title">Finance</span></a>
            </li>
            <li class=" nav-item">
                <a href="service.html"><img src="{% static 'signup/img/icon/financial.png' %}" width="30px;"
                                            height="30px;"></img> &nbsp;<span class="menu-title">Service</span></a>
            </li>


        </ul>

    </div>
</div>
<div class="app-content content">
    <div class="content-wrapper">

        <div class="content-body">

            <div class="card card1">
                <span>Profile</span>
            </div>

            <br>


            <div class="container-fluid box1">
                {% for foo in form_error_field %}
                    <strong>{{ foo|capfirst }}</strong>
                {% endfor %}

                {% for field in form_error %}
                    {% for error in field.errors %}
                            <strong>{{ error|escape }}</strong>
                    {% endfor %}
                {% endfor %}
            </div>


        </div>
    </div>
</div>

<script src="{% static 'signup/js/vendors.min.js' %}" type="text/javascript"></script>
<script src="{% static 'signup/js/main.js' %}" type="text/javascript"></script>

<!--branding-->
<script src="{% static 'signup/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'signup/vendor/jquery-validation/dist/jquery.validate.min.js' %}"></script>

<script src="{% static 'signup/vendor/jquery-steps/jquery.steps.min.js' %}"></script>


<script src="{% static 'signup/js/menu.js' %}"></script>
<script src="{% static 'signup/js/profile-step1.js' %}"></script>
<script src="{% static 'signup/js/profile-step2.js' %}"></script>
<script src="{% static 'signup/js/profile-step3.js' %}"></script>
<script src="{% static 'signup/js/profile-step4.js' %}"></script>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//geodata.solutions/includes/countrystatecity.js"></script>


</body>
</html>

signup/templates/signup/login.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<!-- MATERIAL DESIGN ICONIC FONT -->
		<link rel="stylesheet" href="{% static 'signup1/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}">
		
		<!-- STYLE CSS -->
		<link rel="stylesheet" href="{% static 'signup1/css/login.css' %}">
	</head>

	<body>

		<div class="wrapper">
			<div class="inner">
				<div class="image-holder">
					<img src="{% static 'signup1/images/login.png' %}" alt="">
				</div>
				<form method="post">
			
					{% csrf_token %}
					<h3>Welcome Back To Hobnob</h3>
					<br>
					<div class="form-row">
						{{form.email.label}}
						{{form.email }}
					</div>
					<div class="form-row">
						{{form.password.label}}
						{{form.password}}
					</div>
					<br>
					<button>Login
						<i class="zmdi zmdi-long-arrow-right"></i>
					</button>

					{{ form.errors }}
					
<br><br>
					<h4 style="float:right;">New To Hobnob <a href="{% url 'signup:signup' %}">Signup</a></h4>
					

				</form>
				
			</div>
		</div>


		<script src="{% static 'signup1/js/login.js' %}"></script>
	</body>
</html>

signup/templates/signup/signup.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- MATERIAL DESIGN ICONIC FONT -->
    <link rel="stylesheet" href="{% static 'signup1/fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}">

    <!-- STYLE CSS -->
    <link rel="stylesheet" href="{% static 'signup1/css/login.css' %}">
</head>

<body>

<div class="wrapper">
    <div class="inner">
        <div class="image-holder">
            <img src="{% static 'signup1/images/login.png' %}" alt="">
        </div>

        <form method="POST">
            {% csrf_token %}
            <h3>Welcome To Hobnob</h3>
            
            <div class="form-row">
                {{form.first_name.label}}{{form.first_name}}
                {{form.username.label}} {{form.username}}
                <!-- <input type="text" class="form-control" placeholder="Name" name="name"> -->
                <!-- <input type="email" class="form-control" placeholder="Email"> -->
            </div>
            <div class="form-row">
                {{form.phone_number.label}} {{form.phone_number}}
                <div class="form-holder">
                    {{form.profile_category.label}}{{form.profile_category}}
                    <i class="zmdi zmdi-chevron-down"></i>
                </div>
            </div>

            <div class="form-row">
                {{form.password1.label}}{{ form.password1 }}
                {{form.password2.label}}{{ form.password2 }}
            </div> 

            {{form.errors}}

            <button type="submit">SignUp
                <i class="zmdi zmdi-long-arrow-right"></i>
            </button>
            <br>
            <h4 style="float:right;">Have An Account With Hobnob ? <a href="{% url 'signup:login' %}">Login</a></h4>
        </form>

    </div>
</div>

<script src="{% static 'signup1/js/jquery-3.3.1.min.js'%}"></script>
<script src="{% static 'signup1/js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>